apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend
  namespace: micro-notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      containers:
        - name: notes-backend
          image: micro-notes-backend:local
          ports:
            - containerPort: 5000
