apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: micro-notes-ingress
  namespace: micro-notes
spec:
  ingressClassName: nginx
  rules:
    - host: micro-notes.local
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: notes-backend
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notes-frontend
                port:
                  number: 80
